export const SpriteData = {
    // Цветовые коды:
    // P = Primary Color (основной цвет костюма)
    // L = Light primary (основной цвет + подсветка)
    // K = Dark primary (основной цвет + тень)
    // B = Black / тёмная ткань
    // W = White / глаза
    // S = Skin светлая (Скорпион, Саб-Зиро, Райден)
    // s = Skin тень светлая
    // T = Skin средняя (Лю Канг)
    // t = Skin тень средняя
    // U = Skin тёмная (Джакс)
    // u = Skin тень тёмная
    // G = Metal светлый (руки Джакса)
    // g = Metal тёмный
    // A = Accent (гарпун Скорпиона, шляпа Райдена, повязка Лю Кана)
    // I = Ice (лёд Саб-Зиро)
    // Z = Reptile skin (зелёный)
    // z = Reptile skin shadow
    // E = Lightning (молния Райдена)
    // H = Highlight / глаза

    scorpion: {
        idle: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBKKKKKKKKKKKKKKKKKKKKBB..............",
                "............BBKKKKPPPPPPPPPPPPPPPPKKKKBB............",
                "...........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "..........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                ".........BKKPPPPPPBBBBBBBBBBBBBBBBPPPPPPKKB.........",
                ".........BKPPPPBBSHHHWWSSSSHHSWSSBBPPPPKKB.........",
                "........BKPPPPBBSHHHWWSSSSHHHSSWSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSSSSSHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSHHHHHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBBSSSSSSSSSSSSSSSSSSBBPPPPKKB........",
                "........BKPPPPBBBBBBBBBBBBBBBBBBBBBBPPPPKKB........",
                ".........BKPPPPPPPPBBBBBBBBBBBBPPPPPPPPKKB.........",
                ".........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                "..........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "...........BBBBKKKKKKKKKKKKKKKKKKKKBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                ".....................BMMMMMMB.......................",
                "...................BBBBBBBBBBBB.....................",
                ".................BBKKKKKKKKKKKKBB...................",
                "...............BBKKKPPPPPPPPPKKKBB..................",
                ".............BBKKPPPPPPPPPPPPPPPKKBB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPLLLLLLPPPPPPPPPKKB..............",
                "..........BKKPPPPPLLLLLLLLLLLPPPPPPPKKB.............",
                ".........BKKPPPPLLLLLLLLLLLLLLLPPPPPPKKB............",
                "........BKKPPPPLLLLMMMBBBMMMLLLLPPPPPPKKB...........",
                "........BKPPPPLLLLMMBBBBBBBMMLLLLPPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLLMMBBBBBBBMMLLLLPPPPPPKKB..........",
                "........BKKPPPPLLLLMMMBBBMMMLLLLPPPPPPKKB............",
                ".........BKKPPPPLLLLLLLLLLLLLLLPPPPPPKKB............",
                "..........BKKPPPPPLLLLLLLLLLLPPPPPPPKKB.............",
                "...........BKKPPPPPPLLLLLLPPPPPPPPPKKB..............",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                ".............BBKKKKKKPPPPPPPKKKKKKBB................",
                "...............BBBBBBPPPPPPPBBBBBB..................",
                "....................PPPPPPPPP.......................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPPPPPPPPPPPPPPPPKKB..............",
                "..........BKKPPPPPPPPPKKKPPPPPPPPPPPKKB.............",
                ".........BKKPPPPPPPPPKKKKKPPPPPPPPPPPKKB............",
                "........BKKPPPPPPPPPKKKKKKKPPPPPPPPPPPKKB...........",
                ".......BKKPPPPPPPPPKKKKKKKKKPPPPPPPPPPPKKB..........",
                ".......BKPPPPPPPPPKKKKKKKKKKKPPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKAAAAAAAAPPKB..........", // гарпун
                ".......BKPPPPPPPPKKKKKKKKKKKKKAAAAAAAAPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BBKKKKPPPPKKKKKKKKKKKKKPPPPKKKKBB............",
                ".........BBBBKKKKKKKKKKKKKKKKKKKKKBBBB..............",
                ".............BBBBBBBBBBBBBBBBBBBBBB.................",
                "...............BMMMMB......BMMMMB...................",
                "..............BMMMMMB......BMMMMMB..................",
                ".............BMMMMMMB......BMMMMMMB.................",
                "............BMMMMMMMB......BMMMMMMMB................",
                "...........BMMMMMMMMB......BMMMMMMMMB...............",
                "..........BMMMMMMMMMB......BMMMMMMMMMB..............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BBBBBBBBBBBB......BBBBBBBBBBBB.............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBBBBBBBBBBBBB....BBBBBBBBBBBBBB............"
            ]
        ],
        crouch: [
            [
                "....................................................",
                "....................................................",
                "....................................................",
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBKKKKKKKKKKKKKKKKKKKKBB..............",
                "............BBKKKKPPPPPPPPPPPPPPPPKKKKBB............",
                "...........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "..........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                ".........BKKPPPPPPBBBBBBBBBBBBBBBBPPPPPPKKB.........",
                ".........BKPPPPBBSHHHWWSSSSHHSWSSBBPPPPKKB.........",
                "........BKPPPPBBSHHHWWSSSSHHHSSWSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSSSSSHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSHHHHHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBBSSSSSSSSSSSSSSSSSSBBPPPPKKB........",
                "........BKPPPPBBBBBBBBBBBBBBBBBBBBBBPPPPKKB........",
                ".........BKPPPPPPPPBBBBBBBBBBBBPPPPPPPPKKB.........",
                ".........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                "..........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "...........BBBBKKKKKKKKKKKKKKKKKKKKBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                "...............BBKKKPPPPPPPPPKKKBB..................",
                ".............BBKKPPPPPPPPPPPPPPPKKBB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "............BKPPPPPPPPPPPPPPPPPPPPPKB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "............BKPPPPPPPPPPPPPPPPPPPPPKB...............",
                "............BBKKKKKKPPPPPPPKKKKKKBB................",
                "..............BBBBBBPPPPPPPBBBBBB..................",
                "..............BMMMMB......BMMMMB...................",
                ".............BMMMMMB......BMMMMMB..................",
                "..........BBBBBBBBBB......BBBBBBBBBB................",
                ".........BBMMMMMMMMBB....BBMMMMMMMMBB...............",
                ".........BBBBBBBBBBBB....BBBBBBBBBBBB...............",
                "..............AAAA..................................", // гарпун на поясе
                "..............AAAA.................................."
            ]
        ],
        punch: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBKKKKKKKKKKKKKKKKKKKKBB..............",
                "............BBKKKKPPPPPPPPPPPPPPPPKKKKBB............",
                "...........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "..........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                ".........BKKPPPPPPBBBBBBBBBBBBBBBBPPPPPPKKB.........",
                ".........BKPPPPBBSHHHWWSSSSHHSWSSBBPPPPKKB.........",
                "........BKPPPPBBSHHHWWSSSSHHHSSWSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSSSSSHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSHHHHHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBBSSSSSSSSSSSSSSSSSSBBPPPPKKB........",
                "........BKPPPPBBBBBBBBBBBBBBBBBBBBBBPPPPKKB........",
                ".........BKPPPPPPPPBBBBBBBBBBBBPPPPPPPPKKB.........",
                ".........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                "..........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "...........BBBBKKKKKKKKKKKKKKKKKKKKBBBB.............",
                ".....................BMMMMMMB.......................",
                "...................BBBBBBBBBBBB.....................",
                ".........BBBBBBBBBBKKKKKKKKKKKKBB...................",
                "......BBBPPPPPPPPPBBKKKPPPPPPPPPKKKBB...............",
                "....BBPPPPPPPPPPPPPPBKKPPPPPPPPPPPPPPPKKBB..........",
                "....BPPPPPPPPPPPPPPPPPBKPPPPPPPPPPPPPPPKKB..........",
                "...BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPPPLLLLLLPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPPPLLLLLLPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "....BKPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "....BBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKBB..........",
                "......BBBPPPPPPPPPBBKKPPPPPPPPPKKKKKBB..............",
                ".........BBBBBBBBBBBBBBBBBBBBBBBBBB.................",
                "....................PPPPPPPPP.......................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPPPPPPPPPPPPPPPPKKB..............",
                "..........BKKPPPPPPPPPKKKPPPPPPPPPPPKKB.............",
                ".........BKKPPPPPPPPPKKKKKPPPPPPPPPPPKKB............",
                "........BKKPPPPPPPPPKKKKKKKPPPPPPPPPPPKKB...........",
                ".......BKKPPPPPPPPPKKKKKKKKKPPPPPPPPPPPKKB..........",
                ".......BKPPPPPPPPPKKKKKKKKKKKPPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKAAAAAAAAPPKB..........", // гарпун летит
                ".......BKPPPPPPPPKKKKKKKKKKKKKAAAAAAAAPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BBKKKKPPPPKKKKKKKKKKKKKPPPPKKKKBB............",
                ".........BBBBKKKKKKKKKKKKKKKKKKKKKBBBB..............",
                ".............BBBBBBBBBBBBBBBBBBBBBB.................",
                "...............BMMMMB......BMMMMB...................",
                "..............BMMMMMB......BMMMMMB..................",
                ".............BMMMMMMB......BMMMMMMB.................",
                "............BMMMMMMMB......BMMMMMMMB................",
                "...........BMMMMMMMMB......BMMMMMMMMB...............",
                "..........BMMMMMMMMMB......BMMMMMMMMMB..............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BBBBBBBBBBBB......BBBBBBBBBBBB.............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBBBBBBBBBBBBB....BBBBBBBBBBBBBB............"
            ]
        ],
    },

    subzero: {
        idle: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBKKKKKKKKKKKKKKKKKKKKBB..............",
                "............BBKKKKPPPPPPPPPPPPPPPPKKKKBB............",
                "...........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "..........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                ".........BKKPPPPPPBBBBBBBBBBBBBBBBPPPPPPKKB.........",
                ".........BKPPPPBBSHHHWWSSSSHHSWSSBBPPPPKKB.........",
                "........BKPPPPBBSHHHWWSSSSHHHSSWSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSSSSSHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSHHHHHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBBSSSSSSSSSSSSSSSSSSBBPPPPKKB........",
                "........BKPPPPBBBBBBBBBBBBBBBBBBBBBBPPPPKKB........",
                ".........BKPPPPPPPPBBBBBBBBBBBBPPPPPPPPKKB.........",
                ".........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                "..........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "...........BBBBKKKKKKKKKKKKKKKKKKKKBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                ".....................BMMMMMMB.......................",
                "...................BBBBBBBBBBBB.....................",
                ".................BBKKKKKKKKKKKKBB...................",
                "...............BBKKKPPPPPPPPPKKKBB..................",
                ".............BBKKPPPPPPPPPPPPPPPKKBB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPLLLLLLPPPPPPPPPKKB..............",
                "..........BKKPPPPPLLLLLLLLLLLPPPPPPPKKB.............",
                ".........BKKPPPPLLLLLLLLLLLLLLLPPPPPPKKB............",
                "........BKKPPPPLLLLMMMBBBMMMLLLLPPPPPPKKB...........",
                "........BKPPPPLLLLMMBBBBBBBMMLLLLPPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLLMMBBBBBBBMMLLLLPPPPPPKKB..........",
                "........BKKPPPPLLLLMMMBBBMMMLLLLPPPPPPKKB............",
                ".........BKKPPPPLLLLLLLLLLLLLLLPPPPPPKKB............",
                "..........BKKPPPPPLLLLLLLLLLLPPPPPPPKKB.............",
                "...........BKKPPPPPPLLLLLLPPPPPPPPPKKB..............",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                ".............BBKKKKKKPPPPPPPKKKKKKBB................",
                "...............BBBBBBPPPPPPPBBBBBB..................",
                "....................PPPPPPPPP.......................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPPPPPPPPPPPPPPPPKKB..............",
                "..........BKKPPPPPPPPPKKKPPPPPPPPPPPKKB.............",
                ".........BKKPPPPPPPPPKKKKKPPPPPPPPPPPKKB............",
                "........BKKPPPPPPPPPKKKKKKKPPPPPPPPPPPKKB...........",
                ".......BKKPPPPPPPPPKKKKKKKKKPPPPPPPPPPPKKB..........",
                ".......BKPPPPPPPPPKKKKKKKKKKKPPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKIIIIIIIIPKB..........", // лёд на груди
                ".......BKPPPPPPPPKKKKKKKKKKKKKIIIIIIIIPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BBKKKKPPPPKKKKKKKKKKKKKPPPPKKKKBB............",
                ".........BBBBKKKKKKKKKKKKKKKKKKKKKBBBB..............",
                ".............BBBBBBBBBBBBBBBBBBBBBB.................",
                "...............BMMMMB......BMMMMB...................",
                "..............BMMMMMB......BMMMMMB..................",
                ".............BMMMMMMB......BMMMMMMB.................",
                "............BMMMMMMMB......BMMMMMMMB................",
                "...........BMMMMMMMMB......BMMMMMMMMB...............",
                "..........BMMMMMMMMMB......BMMMMMMMMMB..............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BBBBBBBBBBBB......BBBBBBBBBBBB.............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBBBBBBBBBBBBB....BBBBBBBBBBBBBB............"
            ]
        ],
        crouch: [
            [
                "....................................................",
                "....................................................",
                "....................................................",
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBKKKKKKKKKKKKKKKKKKKKBB..............",
                "............BBKKKKPPPPPPPPPPPPPPPPKKKKBB............",
                "...........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "..........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                ".........BKKPPPPPPBBBBBBBBBBBBBBBBPPPPPPKKB.........",
                ".........BKPPPPBBSHHHWWSSSSHHSWSSBBPPPPKKB.........",
                "........BKPPPPBBSHHHWWSSSSHHHSSWSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSSSSSHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSHHHHHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBBSSSSSSSSSSSSSSSSSSBBPPPPKKB........",
                "........BKPPPPBBBBBBBBBBBBBBBBBBBBBBPPPPKKB........",
                ".........BKPPPPPPPPBBBBBBBBBBBBPPPPPPPPKKB.........",
                ".........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                "..........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "...........BBBBKKKKKKKKKKKKKKKKKKKKBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                "...............BBKKKPPPPPPPPPKKKBB..................",
                ".............BBKKPPPPPPPPPPPPPPPKKBB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "............BKPPPPPPPPPPPPPPPPPPPPPKB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "............BKPPPPPPPPPPPPPPPPPPPPPKB...............",
                "............BBKKKKKKPPPPPPPKKKKKKBB................",
                "..............BBBBBBPPPPPPPBBBBBB..................",
                "..............BMMMMB......BMMMMB...................",
                ".............BMMMMMB......BMMMMMB..................",
                "..........BBBBBBBBBB......BBBBBBBBBB................",
                ".........BBMMMMMMMMBB....BBMMMMMMMMBB...............",
                ".........BBBBBBBBBBBB....BBBBBBBBBBBB...............",
                "..............IIII..................................", // ледяные шипы
                "..............IIII.................................."
            ]
        ],
        punch: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBKKKKKKKKKKKKKKKKKKKKBB..............",
                "............BBKKKKPPPPPPPPPPPPPPPPKKKKBB............",
                "...........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "..........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                ".........BKKPPPPPPBBBBBBBBBBBBBBBBPPPPPPKKB.........",
                ".........BKPPPPBBSHHHWWSSSSHHSWSSBBPPPPKKB.........",
                "........BKPPPPBBSHHHWWSSSSHHHSSWSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSSSSSHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBSSSSSSHHHHHHHSSSSSSBBPPPPKKB........",
                "........BKPPPPBBSSSSSSSSSSSSSSSSSSBBPPPPKKB........",
                "........BKPPPPBBBBBBBBBBBBBBBBBBBBBBPPPPKKB........",
                ".........BKPPPPPPPPBBBBBBBBBBBBPPPPPPPPKKB.........",
                ".........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                "..........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "...........BBBBKKKKKKKKKKKKKKKKKKKKBBBB.............",
                ".....................BMMMMMMB.......................",
                "...................BBBBBBBBBBBB.....................",
                ".........BBBBBBBBBBKKKKKKKKKKKKBB...................",
                "......BBBPPPPPPPPPBBKKKPPPPPPPPPKKKBB...............",
                "....BBPPPPPPPPPPPPPPBKKPPPPPPPPPPPPPPPKKBB..........",
                "....BPPPPPPPPPPPPPPPPPBKPPPPPPPPPPPPPPPKKB..........",
                "...BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPPPLLLLLLPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPPPLLLLLLPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "....BKPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "....BBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKBB..........",
                "......BBBPPPPPPPPPBBKKPPPPPPPPPKKKKKBB..............",
                ".........BBBBBBBBBBBBBBBBBBBBBBBBBB.................",
                "....................PPPPPPPPP.......................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPPPPPPPPPPPPPPPPKKB..............",
                "..........BKKPPPPPPPPPKKKPPPPPPPPPPPKKB.............",
                ".........BKKPPPPPPPPPKKKKKPPPPPPPPPPPKKB............",
                "........BKKPPPPPPPPPKKKKKKKPPPPPPPPPPPKKB...........",
                ".......BKKPPPPPPPPPKKKKKKKKKPPPPPPPPPPPKKB..........",
                ".......BKPPPPPPPPPKKKKKKKKKKKPPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKIIIIIIIIPKB..........", // ледяной удар
                ".......BKPPPPPPPPKKKKKKKKKKKKKIIIIIIIIPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BBKKKKPPPPKKKKKKKKKKKKKPPPPKKKKBB............",
                ".........BBBBKKKKKKKKKKKKKKKKKKKKKBBBB..............",
                ".............BBBBBBBBBBBBBBBBBBBBBB.................",
                "...............BMMMMB......BMMMMB...................",
                "..............BMMMMMB......BMMMMMB..................",
                ".............BMMMMMMB......BMMMMMMB.................",
                "............BMMMMMMMB......BMMMMMMMB................",
                "...........BMMMMMMMMB......BMMMMMMMMB...............",
                "..........BMMMMMMMMMB......BMMMMMMMMMB..............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BBBBBBBBBBBB......BBBBBBBBBBBB.............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBBBBBBBBBBBBB....BBBBBBBBBBBBBB............"
            ]
        ],
    },

    reptile: {
        idle: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBKKKKKKKKKKKKKKKKKKKKBB..............",
                "............BBKKKKPPPPPPPPPPPPPPPPKKKKBB............",
                "...........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "..........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                ".........BKKPPPPPPBBBBBBBBBBBBBBBBPPPPPPKKB.........",
                ".........BKPPPPBBSHHHWWZZZZHHZWZZBBPPPPKKB.........", // зелёная кожа
                "........BKPPPPBBSHHHWWZZZZHHHZZWZZBBPPPPKKB........",
                "........BKPPPPBZZZZZZZZZZHHHZZZZZZBBPPPPKKB........",
                "........BKPPPPBZZZZZZHHHHHHHZZZZZZBBPPPPKKB........",
                "........BKPPPPBBZZZZZZZZZZZZZZZZZZBBPPPPKKB........",
                "........BKPPPPBBBBBBBBBBBBBBBBBBBBBBPPPPKKB........",
                ".........BKPPPPPPPPBBBBBBBBBBBBPPPPPPPPKKB.........",
                ".........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                "..........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "...........BBBBKKKKKKKKKKKKKKKKKKKKBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                ".....................BMMMMMMB.......................",
                "...................BBBBBBBBBBBB.....................",
                ".................BBKKKKKKKKKKKKBB...................",
                "...............BBKKKPPPPPPPPPKKKBB..................",
                ".............BBKKPPPPPPPPPPPPPPPKKBB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPLLLLLLPPPPPPPPPKKB..............",
                "..........BKKPPPPPLLLLLLLLLLLPPPPPPPKKB.............",
                ".........BKKPPPPLLLLLLLLLLLLLLLPPPPPPKKB............",
                "........BKKPPPPLLLLMMMBBBMMMLLLLPPPPPPKKB...........",
                "........BKPPPPLLLLMMBBBBBBBMMLLLLPPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLMMBBBBBBBBBMMLLLLPPPPPKKB..........",
                "........BKPPPPLLLLMMBBBBBBBMMLLLLPPPPPPKKB..........",
                "........BKKPPPPLLLLMMMBBBMMMLLLLPPPPPPKKB............",
                ".........BKKPPPPLLLLLLLLLLLLLLLPPPPPPKKB............",
                "..........BKKPPPPPLLLLLLLLLLLPPPPPPPKKB.............",
                "...........BKKPPPPPPLLLLLLPPPPPPPPPKKB..............",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                ".............BBKKKKKKPPPPPPPKKKKKKBB................",
                "...............BBBBBBPPPPPPPBBBBBB..................",
                "....................PPPPBBBB........................",
                "....................PPPPBBBB........................",
                "...................BKPPPPPPKB.......................",
                ".................BBKPPPPPPPPKB......................",
                "...............BBKKPPPPPPPPPPKB.....................",
                "..............BKKKPPPPPPPPPPPPKB....................",
                ".............BKKPPPPPPPPPPPPPPPPB...................",
                "............BKKPPPPPPPPPPPPPPPPPPB..................",
                "...........BKKPPPPPPPPPPPPPPPPPPPPB.................",
                "..........BKKPPPPPPPPPKKKPPPPPPPPPPPKKB.............",
                ".........BKKPPPPPPPPPKKKKKPPPPPPPPPPPKKB............",
                "........BKKPPPPPPPPPKKKKKKKPPPPPPPPPPPKKB...........",
                ".......BKKPPPPPPPPPKKKKKKKKKPPPPPPPPPPPKKB..........",
                ".......BKPPPPPPPPPKKKKKKKKKKKPPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BBKKKKPPPPKKKKKKKKKKKKKPPPPKKKKBB............",
                ".........BBBBKKKKKKKKKKKKKKKKKKKKKBBBB..............",
                ".............BBBBBBBBBBBBBBBBBBBBBB.................",
                "...............BMMMMB......BMMMMB...................",
                "..............BMMMMMB......BMMMMMB..................",
                ".............BMMMMMMB......BMMMMMMB.................",
                "............BMMMMMMMB......BMMMMMMMB................",
                "...........BMMMMMMMMB......BMMMMMMMMB...............",
                "..........BMMMMMMMMMB......BMMMMMMMMMB..............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BBBBBBBBBBBB......BBBBBBBBBBBB.............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBBBBBBBBBBBBB....BBBBBBBBBBBBBB............"
            ]
        ],
        crouch: [
            [
                "....................................................",
                "....................................................",
                "....................................................",
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBKKKKKKKKKKKKKKKKKKKKBB..............",
                "............BBKKKKPPPPPPPPPPPPPPPPKKKKBB............",
                "...........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "..........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                ".........BKKPPPPPPBBBBBBBBBBBBBBBBPPPPPPKKB.........",
                ".........BKPPPPBBSHHHWWZZZZHHZWZZBBPPPPKKB.........",
                "........BKPPPPBBSHHHWWZZZZHHHZZWZZBBPPPPKKB........",
                "........BKPPPPBZZZZZZZZZZHHHZZZZZZBBPPPPKKB........",
                "........BKPPPPBZZZZZZHHHHHHHZZZZZZBBPPPPKKB........",
                "........BKPPPPBBZZZZZZZZZZZZZZZZZZBBPPPPKKB........",
                "........BKPPPPBBBBBBBBBBBBBBBBBBBBBBPPPPKKB........",
                ".........BKPPPPPPPPBBBBBBBBBBBBPPPPPPPPKKB.........",
                ".........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                "..........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "...........BBBBKKKKKKKKKKKKKKKKKKKKBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                "...............BBKKKPPPPPPPPPKKKBB..................",
                ".............BBKKPPPPPPPPPPPPPPPKKBB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "............BKPPPPPPPPPPPPPPPPPPPPPKB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "...........BKPPPPPPPPPPPPPPPPPPPPPPPB...............",
                "............BKPPPPPPPPPPPPPPPPPPPPPKB...............",
                "............BBKKKKKKPPPPPPPKKKKKKBB................",
                "..............BBBBBBPPPPPPPBBBBBB..................",
                "..............BMMMMB......BMMMMB...................",
                ".............BMMMMMB......BMMMMMB..................",
                "..........BBBBBBBBBB......BBBBBBBBBB................",
                ".........BBMMMMMMMMBB....BBMMMMMMMMBB...............",
                ".........BBBBBBBBBBBB....BBBBBBBBBBBB...............",
                "..............ZZZZ..................................", // язык
                "..............ZZZZ.................................."
            ]
        ],
        punch: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBKKKKKKKKKKKKKKKKKKKKBB..............",
                "............BBKKKKPPPPPPPPPPPPPPPPKKKKBB............",
                "...........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "..........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                ".........BKKPPPPPPBBBBBBBBBBBBBBBBPPPPPPKKB.........",
                ".........BKPPPPBBSHHHWWZZZZHHZWZZBBPPPPKKB.........",
                "........BKPPPPBBSHHHWWZZZZHHHZZWZZBBPPPPKKB........",
                "........BKPPPPBZZZZZZZZZZHHHZZZZZZBBPPPPKKB........",
                "........BKPPPPBZZZZZZHHHHHHHZZZZZZBBPPPPKKB........",
                "........BKPPPPBBZZZZZZZZZZZZZZZZZZBBPPPPKKB........",
                "........BKPPPPBBBBBBBBBBBBBBBBBBBBBBPPPPKKB........",
                ".........BKPPPPPPPPBBBBBBBBBBBBPPPPPPPPKKB.........",
                ".........BKKPPPPPPPPPPPPPPPPPPPPPPPPPPKKB..........",
                "..........BKKKPPPPPPPPPPPPPPPPPPPPPPKKKB...........",
                "...........BBBBKKKKKKKKKKKKKKKKKKKKBBBB.............",
                ".....................BMMMMMMB.......................",
                "...................BBBBBBBBBBBB.....................",
                ".........BBBBBBBBBBKKKKKKKKKKKKBB...................",
                "......BBBPPPPPPPPPBBKKKPPPPPPPPPKKKBB...............",
                "....BBPPPPPPPPPPPPPPBKKPPPPPPPPPPPPPPPKKBB..........",
                "....BPPPPPPPPPPPPPPPPPBKPPPPPPPPPPPPPPPKKB..........",
                "...BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPPPLLLLLLPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPLLLLLLLLLLLPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "..BPPPPPPLLLLLLPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "....BKPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKB.........",
                "....BBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKKBB..........",
                "......BBBPPPPPPPPPBBKKPPPPPPPPPKKKKKBB..............",
                ".........BBBBBBBBBBBBBBBBBBBBBBBBBB.................",
                "....................PPPPPPPPP.......................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPPPPPPPPPPPPPPPPKKB..............",
                "..........BKKPPPPPPPPPKKKPPPPPPPPPPPKKB.............",
                ".........BKKPPPPPPPPPKKKKKPPPPPPPPPPPKKB............",
                "........BKKPPPPPPPPPKKKKKKKPPPPPPPPPPPKKB...........",
                ".......BKKPPPPPPPPPKKKKKKKKKPPPPPPPPPPPKKB..........",
                ".......BKPPPPPPPPPKKKKKKKKKKKPPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKZZZZZZZZPKB..........", // зелёные когти
                ".......BKPPPPPPPPKKKKKKKKKKKKKZZZZZZZZPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BBKKKKPPPPKKKKKKKKKKKKKPPPPKKKKBB............",
                ".........BBBBKKKKKKKKKKKKKKKKKKKKKBBBB..............",
                ".............BBBBBBBBBBBBBBBBBBBBBB.................",
                "...............BMMMMB......BMMMMB...................",
                "..............BMMMMMB......BMMMMMB..................",
                ".............BMMMMMMB......BMMMMMMB.................",
                "............BMMMMMMMB......BMMMMMMMB................",
                "...........BMMMMMMMMB......BMMMMMMMMB...............",
                "..........BMMMMMMMMMB......BMMMMMMMMMB..............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BBBBBBBBBBBB......BBBBBBBBBBBB.............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBBBBBBBBBBBBB....BBBBBBBBBBBBBB............"
            ]
        ],
    },

    liukang: {
        idle: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBMMMMMMMMMMMMMMMMMMMMBB..............",
                "............BBMMMMMMMMMMMMMMMMMMMMMMMMBB............",
                "...........BMMMMMMTTTTTTTTTTTTTTMMMMMMMMB...........", // средняя кожа
                "..........BMMMMTTTTTTTTTTTTTTTTTTTTMMMMMMB..........",
                ".........BMMMTTTTTTTTTTTTTTTTTTTTTTTTMMMMMB.........",
                ".........BMTTTTTTHHHWWTTTTHHTWSSHHHHTTMMMMB.........",
                "........BMTTTTTTHHHWWTTTTHHHSSWSSHHHHTTMMMMB........",
                "........BMTTTTTTTTTTTTTTTHHHTTTTTTTTTTMMMMB........",
                "........BMTTTTTTTTTTHHHHHHHHHTTTTTTTTTMMMMB........",
                "........BMTTTTTTTTTTTTTTTTTTTTTTTTTTTTMMMMB........",
                "........BMMMMTTTTTTTTTTTTTTTTTTTTTTTTMMMMMB........",
                ".........BMMMMMMTTTTTTTTTTTTTTTTTTMMMMMMMB.........",
                "..........BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB..........",
                "...........BBBBMMMMMMMMMMMMMMMMMMMMBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                ".....................BAAAAAAB.......................", // красная повязка
                "...................BBAAAAAAAABB.....................",
                ".................BBAAAAAAAAAAAABB...................",
                "...............BBAAAAAAAAAAAAAAAABB..................",
                ".............BBAAAAAAAAAAAAAAAAAAAABB................",
                "............BAAAAAAAAAAAAAAAAAAAAAAAB...............",
                "...........BAAAAAAAAAAAAAAAAAAAAAAAAAB..............",
                "..........BAAAAAAAAAAAAAAAAAAAAAAAAAAAB.............",
                ".........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB............",
                "........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB...........",
                "........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB...........",
                "........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB...........",
                "........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB...........",
                "........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB...........",
                "........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB...........",
                "........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB...........",
                "........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB...........",
                "........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB...........",
                ".........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB............",
                ".........BAAAAAAAAAAAAAAAAAAAAAAAAAAAB.............",
                "..........BAAAAAAAAAAAAAAAAAAAAAAAAAB..............",
                "...........BAAAAAAAAAAAAAAAAAAAAAAAB...............",
                "............BAAAAAAAAAAAAAAAAAAAAAB................",
                ".............BBAAAAAAAAAAAAAAAAAAB.................",
                "...............BBBBBBPPPPPPPBBBBBB..................",
                "....................PPPPPPPPP.......................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPPPPPPPPPPPPPPPPKKB..............",
                "..........BKKPPPPPPPPPKKKPPPPPPPPPPPKKB.............",
                ".........BKKPPPPPPPPPKKKKKPPPPPPPPPPPKKB............",
                "........BKKPPPPPPPPPKKKKKKKPPPPPPPPPPPKKB...........",
                ".......BKKPPPPPPPPPKKKKKKKKKPPPPPPPPPPPKKB..........",
                ".......BKPPPPPPPPPKKKKKKKKKKKPPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BBKKKKPPPPKKKKKKKKKKKKKPPPPKKKKBB............",
                ".........BBBBKKKKKKKKKKKKKKKKKKKKKBBBB..............",
                ".............BBBBBBBBBBBBBBBBBBBBBB.................",
                "...............BBBBB.......BBBBB....................",
                "..............BBBBBB.......BBBBBB...................",
                ".............BBBBBBB.......BBBBBBB..................",
                "............BBBBBBBB.......BBBBBBBB.................",
                "...........BBBBBBBBB.......BBBBBBBBB................",
                "..........BBBBBBBBBB.......BBBBBBBBBB...............",
                ".........BBBBBBBBBBB.......BBBBBBBBBBB..............",
                ".........BBBBBBBBBBB.......BBBBBBBBBBB..............",
                ".........BBBBBBBBBBB.......BBBBBBBBBBB..............",
                "........BBBBBBBBBBBB......BBBBBBBBBBBB..............",
                "........BBBBBBBBBBBB......BBBBBBBBBBBB..............",
                "........BBBBBBBBBBBB......BBBBBBBBBBBB.............."
            ]
        ],
        crouch: [
            [
                "....................................................",
                "....................................................",
                "....................................................",
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBMMMMMMMMMMMMMMMMMMMMBB..............",
                "............BBMMMMMMMMMMMMMMMMMMMMMMMMBB............",
                "...........BMMMMMMTTTTTTTTTTTTTTMMMMMMMMB...........",
                "..........BMMMMTTTTTTTTTTTTTTTTTTTTMMMMMMB..........",
                ".........BMMMTTTTTTTTTTTTTTTTTTTTTTTTMMMMMB.........",
                ".........BMTTTTTTHHHWWTTTTHHTWSSHHHHTTMMMMB.........",
                "........BMTTTTTTHHHWWTTTTHHHSSWSSHHHHTTMMMMB........",
                "........BMTTTTTTTTTTTTTTTHHHTTTTTTTTTTMMMMB........",
                "........BMTTTTTTTTTTHHHHHHHHHTTTTTTTTTMMMMB........",
                "........BMTTTTTTTTTTTTTTTTTTTTTTTTTTTTMMMMB........",
                "........BMMMMTTTTTTTTTTTTTTTTTTTTTTTTMMMMMB........",
                ".........BMMMMMMTTTTTTTTTTTTTTTTTTMMMMMMMB.........",
                "..........BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB..........",
                "...........BBBBMMMMMMMMMMMMMMMMMMMMBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                ".....................BAAAAAAB.......................",
                "...................BBAAAAAAAABB.....................",
                ".................BBAAAAAAAAAAAABB...................",
                "...............BBAAAAAAAAAAAAAAAABB..................",
                ".............BBAAAAAAAAAAAAAAAAAAAABB................",
                "............BAAAAAAAAAAAAAAAAAAAAAAAB...............",
                "...........BAAAAAAAAAAAAAAAAAAAAAAAAAB..............",
                "..........BAAAAAAAAAAAAAAAAAAAAAAAAAAAB.............",
                "..........BAAAAAAAAAAAAAAAAAAAAAAAAAAAB.............",
                "...........BAAAAAAAAAAAAAAAAAAAAAAAAAB...............",
                "............BAAAAAAAAAAAAAAAAAAAAAAAB................",
                ".............BBAAAAAAAAAAAAAAAAAAB.................",
                "...............BBBBBBPPPPPPPBBBBBB..................",
                "....................PPPPPPPPP.......................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BBBBBBB.......BBBBBBB.................",
                ".............BBBBBBBB.......BBBBBBBB................",
                ".............BBBBBBBB.......BBBBBBBB................",
                "..............AAAA..................................", // повязка видна
                "..............AAAA.................................."
            ]
        ],
        punch: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBMMMMMMMMMMMMMMMMMMMMBB..............",
                "............BBMMMMMMMMMMMMMMMMMMMMMMMMBB............",
                "...........BMMMMMMTTTTTTTTTTTTTTMMMMMMMMB...........",
                "..........BMMMMTTTTTTTTTTTTTTTTTTTTMMMMMMB..........",
                ".........BMMMTTTTTTTTTTTTTTTTTTTTTTTTMMMMMB.........",
                ".........BMTTTTTTHHHWWTTTTHHTWSSHHHHTTMMMMB.........",
                "........BMTTTTTTHHHWWTTTTHHHSSWSSHHHHTTMMMMB........",
                "........BMTTTTTTTTTTTTTTTHHHTTTTTTTTTTMMMMB........",
                "........BMTTTTTTTTTTHHHHHHHHHTTTTTTTTTMMMMB........",
                "........BMTTTTTTTTTTTTTTTTTTTTTTTTTTTTMMMMB........",
                "........BMMMMTTTTTTTTTTTTTTTTTTTTTTTTMMMMMB........",
                ".........BMMMMMMTTTTTTTTTTTTTTTTTTMMMMMMMB.........",
                "..........BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB..........",
                "...........BBBBMMMMMMMMMMMMMMMMMMMMBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                ".....................BAAAAAAB.......................",
                "......BBBBBBBBBBBBBTTBTTTTTTTTT.....................",
                "....BBTTTTTTTTTTTTTBBTTTTTTTTT......................",
                "....BTTTTTTTTTTTTTTTTTTTTTTTTT......................",
                "..BBTTTTTTTTTTTTTTTTTTTTTTTTTT......................",
                "..BTTTTTTTTTTTTTTTTTTTTTTTTTTT......................",
                "..BTTTTTTTTTLLLLLLTTTTTTTTTTTT......................",
                "..BTTTTTTTLLLLLLLLLLLTTTTTTTTT......................",
                "..BTTTTTLLLLLLLLLLLLLLLTTTTTTT......................",
                "..BTTTLLLLLLLLLLLLLLLLLLLTTTT.......................",
                "..BTTTLLLLLLLLLLLLLLLLLLLTTTT.......................",
                "..BTTTTTLLLLLLLLLLLLLLLTTTTTTT......................",
                "..BTTTTTTTLLLLLLLLLLLTTTTTTTTT......................",
                "..BBTTTTTTTTTLLLLLTTTTTTTTTTT......................",
                "....BTTTTTTTTTTTTTTTTTTTTTTTTT......................",
                "....BBTTTTTTTTTTTTTTTTTTTTTTT.......................",
                "......BBBBBBBBBBBBBBBBBBBBBBB.......................",
                "...................BBBBBBPPPPPPPBBBBBB..............",
                "....................PPPPPPPPP.......................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKBBBBB.......BBBBBBB.................",
                ".............BBBBBBBB.......BBBBBBBB................",
                ".............BBBBBBBB.......BBBBBBBB................",
                "..............AAAA..................................", // удар ногой
                "..............AAAA.................................."
            ]
        ],
    },

    jax: {
        idle: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBMMMMMMMMMMMMMMMMMMMMBB..............",
                "............BBMMMMMMMMMMMMMMMMMMMMMMMMBB............",
                "...........BMMMMMMUUUUUUUUUUUUUUMMMMMMMMB...........", // тёмная кожа
                "..........BMMMMUUUUUUUUUUUUUUUUUUUUMMMMMMB..........",
                ".........BMMMUUUUUUUUUUUUUUUUUUUUUUUUMMMMMB.........",
                ".........BMUUUUUUHHHWWUUUUHHUWSSHHHHUUMMMMB.........",
                "........BMUUUUUUHHHWWUUUUHHHUSWSSHHHHUUMMMMB........",
                "........BMUUUUUUUUUUUUUUUHHHUUUUUUUUUUMMMMB........",
                "........BMUUUUUUUUUHHHHHHHHHUUUUUUUUUUMMMMB........",
                "........BMUUUUUUUUUUUUUUUUUUUUUUUUUUUUMMMMB........",
                "........BMMMMUUUUUUUUUUUUUUUUUUUUUUUUMMMMMB........",
                ".........BMMMMMMUUUUUUUUUUUUUUUUUUMMMMMMMB.........",
                "..........BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB..........",
                "...........BBBBMMMMMMMMMMMMMMMMMMMMBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                ".....................BGGGGGGB.......................", // металлические руки
                "...................BBGGGGGGGGBB.....................",
                ".................BBGGGGGGGGGGGGBB...................",
                "...............BBGGGGGGGGGGGGGGGGBB.................",
                ".............BBGGGGGGGGGGGGGGGGGGGGBB................",
                "............BGGGGGGGGGGGGGGGGGGGGGGGGB...............",
                "...........BGGGGGGGGGGGGGGGGGGGGGGGGGGB..............",
                "..........BGGGGGGGGGGGGGGGGGGGGGGGGGGGGB.............",
                ".........BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB............",
                ".........BGGGGGGGGUUUUUUUUUUUUUUGGGGGGGGB............", // торс
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                ".........BGGGGGGGUUUUUUUUUUUUUUUUGGGGGGGB............",
                "...............BBBBBBPPPPPPPBBBBBB..................",
                "....................PPPPPPPPP.......................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPPPPPPPPPPPPPPPPKKB..............",
                "..........BKKPPPPPPPPPKKKPPPPPPPPPPPKKB.............",
                ".........BKKPPPPPPPPPKKKKKPPPPPPPPPPPKKB............",
                "........BKKPPPPPPPPPKKKKKKKPPPPPPPPPPPKKB...........",
                ".......BKKPPPPPPPPPKKKKKKKKKPPPPPPPPPPPKKB..........",
                ".......BKPPPPPPPPPKKKKKKKKKKKPPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BBKKKKPPPPKKKKKKKKKKKKKPPPPKKKKBB............",
                ".........BBBBKKKKKKKKKKKKKKKKKKKKKBBBB..............",
                ".............BBBBBBBBBBBBBBBBBBBBBB.................",
                "...............BMMMMB......BMMMMB...................",
                "..............BMMMMMB......BMMMMMB..................",
                ".............BMMMMMMB......BMMMMMMB.................",
                "............BMMMMMMMB......BMMMMMMMB................",
                "...........BMMMMMMMMB......BMMMMMMMMB...............",
                "..........BMMMMMMMMMB......BMMMMMMMMMB..............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BBBBBBBBBBBB......BBBBBBBBBBBB.............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBBBBBBBBBBBBB....BBBBBBBBBBBBBB............"
            ]
        ],
        crouch: [
            [
                "....................................................",
                "....................................................",
                "....................................................",
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBMMMMMMMMMMMMMMMMMMMMBB..............",
                "............BBMMMMMMMMMMMMMMMMMMMMMMMMBB............",
                "...........BMMMMMMUUUUUUUUUUUUUUMMMMMMMMB...........",
                "..........BMMMMUUUUUUUUUUUUUUUUUUUUMMMMMMB..........",
                ".........BMMMUUUUUUUUUUUUUUUUUUUUUUUUMMMMMB.........",
                ".........BMUUUUUUHHHWWUUUUHHUWSSHHHHUUMMMMB.........",
                "........BMUUUUUUHHHWWUUUUHHHUSWSSHHHHUUMMMMB........",
                "........BMUUUUUUUUUUUUUUUHHHUUUUUUUUUUMMMMB........",
                "........BMUUUUUUUUUHHHHHHHHHUUUUUUUUUUMMMMB........",
                "........BMUUUUUUUUUUUUUUUUUUUUUUUUUUUUMMMMB........",
                "........BMMMMUUUUUUUUUUUUUUUUUUUUUUUUMMMMMB........",
                ".........BMMMMMMUUUUUUUUUUUUUUUUUUMMMMMMMB.........",
                "..........BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB..........",
                "...........BBBBMMMMMMMMMMMMMMMMMMMMBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                ".....................BGGGGGGB.......................",
                "...................BBGGGGGGGGBB.....................",
                ".................BBGGGGGGGGGGGGBB...................",
                "...............BBGGGGGGGGGGGGGGGGBB.................",
                ".............BBGGGGGGGGGGGGGGGGGGGGBB................",
                "............BGGGGGGGGGGGGGGGGGGGGGGGGB...............",
                "...........BGGGGGGGGGGGGGGGGGGGGGGGGGGB..............",
                "..........BGGGGGGGGGGGGGGGGGGGGGGGGGGGGB.............",
                ".........BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGB.............",
                "..........BBBBBBGGGGGGGGGGGGGGGGGGGGBB..............",
                "............BBBBBBBBBBBBBBBBBBBBBBBB................",
                "...............BBBBBBPPPPPPPBBBBBB..................",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                ".............BBMMMMMMMMMMBB....BBMMMMMMMMMMBB.......",
                ".............BBBBBBBBBBBBBB....BBBBBBBBBBBBBB.......",
                "..............GGGG..................................", // металлические руки
                "..............GGGG.................................."
            ]
        ],
        punch: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBBBBBBBBBBBBBBBBBB................",
                "..............BBMMMMMMMMMMMMMMMMMMMMBB..............",
                "............BBMMMMMMMMMMMMMMMMMMMMMMMMBB............",
                "...........BMMMMMMUUUUUUUUUUUUUUMMMMMMMMB...........",
                "..........BMMMMUUUUUUUUUUUUUUUUUUUUMMMMMMB..........",
                ".........BMMMUUUUUUUUUUUUUUUUUUUUUUUUMMMMMB.........",
                ".........BMUUUUUUHHHWWUUUUHHUWSSHHHHUUMMMMB.........",
                "........BMUUUUUUHHHWWUUUUHHHUSWSSHHHHUUMMMMB........",
                "........BMUUUUUUUUUUUUUUUHHHUUUUUUUUUUMMMMB........",
                "........BMUUUUUUUUUHHHHHHHHHUUUUUUUUUUMMMMB........",
                "........BMUUUUUUUUUUUUUUUUUUUUUUUUUUUUMMMMB........",
                "........BMMMMUUUUUUUUUUUUUUUUUUUUUUUUMMMMMB........",
                ".........BMMMMMMUUUUUUUUUUUUUUUUUUMMMMMMMB.........",
                "..........BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB..........",
                "...........BBBBMMMMMMMMMMMMMMMMMMMMBBBB.............",
                "...............BBBBBBBBBBBBBBBBBBBB.................",
                ".................BBBBBBBBBBBBBBBBBBBBGGGGGGGGGGGGG..",
                "...............BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                ".............BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                "...........BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                "..........BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                "..........BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                "..........BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                "..........BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                "..........BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                "..........BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                "...........BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                ".............BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
                "...............BBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..",
                ".................BBBBBBBBBBBBBBBBBBBBGGGGGGGGGGGG...",
                ".....................BBBBBBPPPPPPPBBBBBB............",
                "....................PPPPPPPPP.......................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                ".............BBMMMMMMMMMMBB....BBMMMMMMMMMMBB.......",
                ".............BBBBBBBBBBBBBB....BBBBBBBBBBBBBB.......",
                "..............GGGGGGGGGGGGGGGGGGGGGGGGGGGG.........", // мощный удар
                "..............GGGGGGGGGGGGGGGGGGGGGGGGGGGG........."
            ]
        ],
    },

    raiden: {
        idle: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBAAAAAAAAAAAAAAABBB...............",
                "..............BBAAAAAAAAAAAAAAAAAAAAABB.............",
                "............BBAAAAAAAAAAAAAAAAAAAAAAAAABB...........",
                "...........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB..........",
                "..........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB.........",
                "..........BAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAB.........",
                "...........BAAAAAABSSSSSSSSSSSSSSSSBAAAAAAB.........",
                "............BAAAABSSSSSSSSSSSSSSSSSSBAAAAB..........",
                ".............BAABSSSSSHHHWWSSSSHHSWSBAAB............",
                "..............BBSSSSSHHHWWSSSSHHHSSWSSBB............",
                "..............BBSSSSSSSSSSSSSSSHHHSSSSBB............",
                "..............BBSSSSSSSSSSHHHHHHHHHSSSBB............",
                "..............BBSSSSSSSSSSSSSSSSSSSSSSBB............",
                "...............BBSSSSSSSSSSSSSSSSSSSSBB.............",
                "................BBSSSSSSSSSSSSSSSSSSBB..............",
                "..................BBBBBBBBBBBBBBBBBB................",
                "....................BMMMMMMMMMMMMB..................",
                "....................PPPPPPPPPPPPPP..................",
                "...................BPPPPPPPPPPPPPPB.................",
                "..................BPPPPPPPPPPPPPPPPB................",
                ".................BPPPPPPPPPPPPPPPPPPB...............",
                "................BPPPPPPPPPPPPPPPPPPPPB..............",
                "...............BPPPPPPPPPPPPPPPPPPPPPPB.............",
                "..............BPPPPPPPPPPPPPPPPPPPPPPPPB............",
                ".............BPPPPPPPPPPPPPPPPPPPPPPPPPPB...........",
                "............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPB..........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPB..........",
                ".............BPPPPPPPPPPPPPPPPPPPPPPPPPPB...........",
                "..............BPPPPPPPPPPPPPPPPPPPPPPPPB............",
                "...............BPPPPPPPPPPPPPPPPPPPPPPB.............",
                "................BPPPPPPPPPPPPPPPPPPPPB..............",
                ".................BBPPPPPPPPPPPPPPPPBB...............",
                "...................BBPPPPPPPPPPPPBB.................",
                ".....................BBBBBBBBBBBB...................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                "............BKKPPPPPPPPPPPPPPPPPPPKKB...............",
                "...........BKKPPPPPPPPPPPPPPPPPPPPPKKB..............",
                "..........BKKPPPPPPPPPKKKPPPPPPPPPPPKKB.............",
                ".........BKKPPPPPPPPPKKKKKPPPPPPPPPPPKKB............",
                "........BKKPPPPPPPPPKKKKKKKPPPPPPPPPPPKKB...........",
                ".......BKKPPPPPPPPPKKKKKKKKKPPPPPPPPPPPKKB..........",
                ".......BKPPPPPPPPPKKKKKKKKKKKPPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKEEEEEEEEEEB..........", // молнии
                ".......BKPPPPPPPPKKKKKKKKKKKKKEEEEEEEEEEB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BKPPPPPPPPKKKKKKKKKKKKKPPPPPPPPPPKB..........",
                ".......BBKKKKPPPPKKKKKKKKKKKKKPPPPKKKKBB............",
                ".........BBBBKKKKKKKKKKKKKKKKKKKKKBBBB..............",
                ".............BBBBBBBBBBBBBBBBBBBBBB.................",
                "...............BMMMMB......BMMMMB...................",
                "..............BMMMMMB......BMMMMMB..................",
                ".............BMMMMMMB......BMMMMMMB.................",
                "............BMMMMMMMB......BMMMMMMMB................",
                "...........BMMMMMMMMB......BMMMMMMMMB...............",
                "..........BMMMMMMMMMB......BMMMMMMMMMB..............",
                ".........BMMMMMMMMMMB......BMMMMMMMMMMB.............",
                ".........BBBBBBBBBBBB......BBBBBBBBBBBB.............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBMMMMMMMMMMBB....BBMMMMMMMMMMBB............",
                "........BBBBBBBBBBBBBB....BBBBBBBBBBBBBB............"
            ]
        ],
        crouch: [
            [
                "....................................................",
                "....................................................",
                "....................BBBBBBBBBBBB....................",
                "................BBBAAAAAAAAAAAAAAABBB...............",
                "..............BBAAAAAAAAAAAAAAAAAAAAABB.............",
                "............BBAAAAAAAAAAAAAAAAAAAAAAAAABB...........",
                "...........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB..........",
                "..........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB.........",
                "..........BAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAB.........",
                "...........BAAAAAABSSSSSSSSSSSSSSSSBAAAAAAB.........",
                "............BAAAABSSSSSSSSSSSSSSSSSSBAAAAB..........",
                ".............BAABSSSSSHHHWWSSSSHHSWSBAAB............",
                "..............BBSSSSSHHHWWSSSSHHHSSWSSBB............",
                "..............BBSSSSSSSSSSSSSSSHHHSSSSBB............",
                "..............BBSSSSSSSSSSHHHHHHHHHSSSBB............",
                "..............BBSSSSSSSSSSSSSSSSSSSSSSBB............",
                "...............BBSSSSSSSSSSSSSSSSSSSSBB.............",
                "................BBSSSSSSSSSSSSSSSSSSBB..............",
                "..................BBBBBBBBBBBBBBBBBB................",
                "....................BMMMMMMMMMMMMB..................",
                "...................BPPPPPPPPPPPPPPB.................",
                "..................BPPPPPPPPPPPPPPPPB................",
                ".................BPPPPPPPPPPPPPPPPPPB...............",
                "................BPPPPPPPPPPPPPPPPPPPPB..............",
                "...............BPPPPPPPPPPPPPPPPPPPPPPB.............",
                "..............BPPPPPPPPPPPPPPPPPPPPPPPPB............",
                ".............BPPPPPPPPPPPPPPPPPPPPPPPPPPB...........",
                "............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPB..........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "...........BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB.........",
                "............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPB..........",
                ".............BPPPPPPPPPPPPPPPPPPPPPPPPPPB...........",
                "..............BPPPPPPPPPPPPPPPPPPPPPPPPB............",
                "...............BPPPPPPPPPPPPPPPPPPPPPPB.............",
                "................BPPPPPPPPPPPPPPPPPPPPB..............",
                ".................BBPPPPPPPPPPPPPPPPBB...............",
                "...................BBPPPPPPPPPPPPBB.................",
                ".....................BBBBBBBBBBBB...................",
                "..................BBBBBBBBBBBBBBBBBBBB..............",
                ".................BBMMMMMMMMMMBB....BBMMMMMMMMMMBB...",
                ".................BBBBBBBBBBBBBB....BBBBBBBBBBBBBB...",
                "..................EEEEEEEEEEEE......................", // молнии вокруг
                "..................EEEEEEEEEEEE......................"
            ]
        ],
        punch: [
            [
                "....................BBBBBBBBBBBB....................",
                "................BBBAAAAAAAAAAAAAAABBB...............",
                "..............BBAAAAAAAAAAAAAAAAAAAAABB.............",
                "............BBAAAAAAAAAAAAAAAAAAAAAAAAABB...........",
                "...........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB..........",
                "..........BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB.........",
                "..........BAAAAAAAABBBBBBBBBBBBBBBBAAAAAAAB.........",
                "...........BAAAAAABSSSSSSSSSSSSSSSSBAAAAAAB.........",
                "............BAAAABSSSSSSSSSSSSSSSSSSBAAAAB..........",
                "............BAABSSSSSHHHWWSSSSHHSWSBAAB.............",
                ".............BBSSSSSHHHWWSSSSHHHSSWSSBB.............",
                "............BBSSSSSSSSSSSSSSSHHHSSSSBB..............",
                "............BBSSSSSSSSSSHHHHHHHHHSSSBB..............",
                "............BBSSSSSSSSSSSSSSSSSSSSSSBB..............",
                ".............BBSSSSSSSSSSSSSSSSSSSSBB...............",
                "..............BBSSSSSSSSSSSSSSSSSSBB................",
                "................BBBBBBBBBBBBBBBBBB..................",
                "....................PPPPPPPPPPPPPPBBBBBBBBBBBBBBBB..",
                "...................BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBB.",
                "..................BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBB",
                ".................BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "................BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "...............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "..............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                ".............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                ".............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "..............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "...............BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "................BPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                ".................BBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.",
                "...................BBPPPPPPPPPPPPBBBBBBBBBBBBBBBBBB.",
                ".....................BBBBBBBBBBBB...................",
                "...................BKPPPPPPPKB......................",
                ".................BBKPPPPPPPPPKBB....................",
                "...............BBKKPPPPPPPPPPPKKBB..................",
                "..............BKKKPPPPPPPPPPPPPKKKB.................",
                ".............BKKPPPPPPPPPPPPPPPPPKKB................",
                ".............BBMMMMMMMMMMBB....BBMMMMMMMMMMBB.......",
                ".............BBBBBBBBBBBBBB....BBBBBBBBBBBBBB.......",
                "..............EEEEEEEEEEEEEEEEEEEEEEEEEEEE.........", // электрический разряд
                "..............EEEEEEEEEEEEEEEEEEEEEEEEEEEE........."
            ]
        ],
    }
};

// Функция получения цвета пикселя (остаётся без изменений)
export function getPixelColor(charId, pixelCode, primaryColor) {
    if (pixelCode === '.') return null;

    const colors = {
        'B': '#111111',  // чёрный
        'D': '#1a1a1a',  // тёмная ткань
        'M': '#333333',  // средний тёмный
        'W': '#ffffff',  // белый / глаза
        'H': '#ffffff',  // блик
        // Кожа
        'S': '#fcd2b6',  // светлая (Скорпион, Саб-Зиро, Райден)
        's': '#e0b094',  // тень светлой
        'T': '#edb68b',  // средняя (Лю Канг)
        't': '#c68e5a',  // тень средней
        'U': '#5c3a21',  // тёмная (Джакс)
        'u': '#3d2616',  // тень тёмной
        // Металл
        'G': '#b0b0b0',  // светлый (руки Джакса)
        'g': '#888888',  // тёмный металл
        // Особые
        'A': '#dcd2aa',  // акцент (шляпа, повязка, гарпун)
        'I': '#aaccff',  // лёд (Саб-Зиро)
        'Z': '#6b8e23',  // зелёная кожа (Рептилия)
        'z': '#4a5d1e',  // тень зелёной
        'E': '#ffff99',  // молния (Райден)
    };

    if (pixelCode === 'P') return primaryColor;
    if (pixelCode === 'L') return lightenColor(primaryColor, 30);
    if (pixelCode === 'K') return darkenColor(primaryColor, 30);

    if (charId === 'raiden' && pixelCode === 'A') return '#d2b48c'; // соломенная шляпа
    if (charId === 'liukang' && pixelCode === 'A') return '#cc3333'; // красная повязка
    if (charId === 'scorpion' && pixelCode === 'A') return '#8b4513'; // коричневый гарпун
    if (charId === 'jax' && pixelCode === 'G') return '#c0c0c0';    // серебро
    if (charId === 'jax' && pixelCode === 'g') return '#a0a0a0';    // тень серебра

    return colors[pixelCode] || '#ff00ff';
}

function lightenColor(col, amt) {
    let usePound = false;
    if (col[0] === "#") { col = col.slice(1); usePound = true; }
    let num = parseInt(col, 16);
    let r = (num >> 16) + amt;
    if (r > 255) r = 255; else if (r < 0) r = 0;
    let g = ((num >> 8) & 0x00FF) + amt;
    if (g > 255) g = 255; else if (g < 0) g = 0;
    let b = (num & 0x0000FF) + amt;
    if (b > 255) b = 255; else if (b < 0) b = 0;
    return (usePound ? "#" : "") + ((r << 16) | (g << 8) | b).toString(16).padStart(6, '0');
}

function darkenColor(col, amt) {
    return lightenColor(col, -amt);
}